### PR TITLE
Heat pump 2 zones

### PR DESCRIPTION
**Pull request by kajo23**
Hi

I have big issue with heating pump and I have to control > Set Heat Water Zone1 (C) during heating.

WHEN 
        ..............
AND
        Hot Water Flow => Set Heat Water Zone1 (C) + 1 (C)
THEN
       Set Heat Water Zone1 (C) + 1 (C)

For that I need proper cards

### CODE REVIEW

**Comment by XattSPT** [comment]
@kajo23 I do not understand your need. 

Can U please explain with more detail what you need?

You have an issue? Or are you proposing a merge?

**Comment by kajo23** [comment]
I try to reach you and this was the only way to place pull request.
With the flow above i want to control heating pump because for example. if outside temp is between 0 and 5C my heating pump can not go down below 36Hz. Hot water gets over my target water 34 + 1 =35 degree. When water become 35C pump start to stop then start few times. This result in bad COP. I I can add +1 degree with the flow above i will keep pump to work without stops until room temp is reached. 

My request is to add those parameters in flow cards so i can use them to make a flow witch will control my heating pump.

**Comment by kajo23** [comment]
Flow should looks like:

WHEN
.............. every 5min (example)
AND
Logic:
Hot Water Flow + "is more then or equal to" + Set Heat Water Zone1 (C) + 1 (C)

THEN
Set Heat Water Zone1 (C) + 1 (C)

Hope this is clear now

**Comment by XattSPT** [comment]
@kajo23 Set Heat Water Zone1 can only be set using Settings and is not posible to use throught Flowcards or Variables. 

Sorry for inconvenience.

**Pull request closed without merging**
